-- ============================================================
--  Subcategorias + tipo (despesa/receita) para as categorias
--
--  Evolui a aba "Categorias":
--    • cada categoria ganha um TIPO ('despesa' ou 'receita'), para
--      as Receitas aparecerem na mesma aba, numa seção separada;
--    • cada categoria pode ter SUBCATEGORIAS (opcionais). Todas as
--      categorias podem ter subcategorias.
--
--  As categorias já existentes viram, por padrão, do tipo 'despesa'
--  (são as Categorias do novo modelo). Isolamento por user_id + RLS,
--  no mesmo padrão das demais tabelas.
--
--  COMO RODAR:
--    Supabase  ->  SQL Editor  ->  New query  ->  cole TUDO  ->  Run
--  É seguro rodar mais de uma vez (idempotente).
-- ============================================================

-- ------------------------------------------------------------
-- 1) TIPO da categoria (despesa | receita)
-- ------------------------------------------------------------
alter table public.categorias
  add column if not exists tipo text not null default 'despesa';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'categorias_tipo_chk'
  ) then
    alter table public.categorias
      add constraint categorias_tipo_chk check (tipo in ('despesa', 'receita'));
  end if;
end $$;

-- ------------------------------------------------------------
-- 2) SUBCATEGORIAS (filhas de uma categoria)
-- ------------------------------------------------------------
create table if not exists public.subcategorias (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) default auth.uid(),
  categoria_id bigint not null references public.categorias(id) on delete cascade,
  nome         text not null,
  ordem        int  not null default 0,
  criado_em    timestamptz not null default now()
);

-- um nome de subcategoria é único DENTRO da categoria (por usuário)
create unique index if not exists subcategorias_cat_nome_uidx
  on public.subcategorias (categoria_id, nome);

create index if not exists subcategorias_user_idx
  on public.subcategorias (user_id);

create index if not exists subcategorias_cat_ordem_idx
  on public.subcategorias (categoria_id, ordem);

alter table public.subcategorias enable row level security;

drop policy if exists "proprios dados" on public.subcategorias;
create policy "proprios dados" on public.subcategorias
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ============================================================
--  Pronto. As categorias já existentes ficam como 'despesa';
--  crie categorias de 'receita' e subcategorias direto no app.
-- ============================================================
