-- ============================================================
--  Categorias editáveis pelo usuário (aba "Categorias")
--  Cada pessoa gerencia as próprias categorias: nome, cor e a
--  ORDEM em que aparecem nos dropdowns. Isolamento por user_id + RLS,
--  no mesmo padrão das demais tabelas (ver 2026-06-15-multiusuario.sql).
--
--  COMO RODAR:
--    Supabase  ->  SQL Editor  ->  New query  ->  cole TUDO  ->  Run
--  É seguro rodar mais de uma vez (idempotente).
-- ============================================================

create table if not exists public.categorias (
  id        bigint generated by default as identity primary key,
  user_id   uuid not null references auth.users(id) default auth.uid(),
  nome      text not null,
  cor       text not null default '#9ca3af',
  ordem     int  not null default 0,
  criado_em timestamptz not null default now()
);

-- um nome de categoria é único POR usuário (cada conta tem o seu conjunto)
create unique index if not exists categorias_user_nome_uidx
  on public.categorias (user_id, nome);

create index if not exists categorias_user_ordem_idx
  on public.categorias (user_id, ordem);

alter table public.categorias enable row level security;

drop policy if exists "proprios dados" on public.categorias;
create policy "proprios dados" on public.categorias
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ------------------------------------------------------------
-- Semente: categorias padrão para o DONO atual, se ele ainda não
-- tiver nenhuma. Contas novas são semeadas pelo próprio app na 1ª
-- carga (ver src/lib/categorias.tsx).
-- ------------------------------------------------------------
do $$
declare
  dono uuid := (select id from auth.users where email = 'caio.dbr7@gmail.com');
  defaults text[][] := array[
    array['Moradia','#820ad1'], array['Mercado','#16a34a'], array['Alimentacao','#f59e0b'],
    array['Transporte','#2f6df6'], array['Saude','#e0382b'], array['Academia','#0ea5e9'],
    array['Vestuario','#db2777'], array['Compras','#7c3aed'], array['Assinaturas','#0891b2'],
    array['Lazer','#f97316'], array['Viagem','#6d28d9'], array['Educacao','#059669'],
    array['Servicos','#64748b'], array['Transferencias','#94a3b8'], array['Impostos/Taxas','#b45309'],
    array['Presentes','#ec4899'], array['Pets','#a16207'], array['Corporativo','#334155'],
    array['Outros','#9ca3af']
  ];
  i int;
begin
  if dono is not null and not exists (select 1 from public.categorias where user_id = dono) then
    for i in 1 .. array_length(defaults, 1) loop
      insert into public.categorias (user_id, nome, cor, ordem)
      values (dono, defaults[i][1], defaults[i][2], i - 1);
    end loop;
  end if;
end $$;

-- ============================================================
--  Pronto. Renomear/excluir uma categoria no app reflete nos
--  lançamentos (categoria_manual) e nas regras automaticamente.
-- ============================================================
